version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: dev_navi_api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app/api


  db:
    image: postgres:16.2-alpine3.19
    container_name: dev_navi_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5430:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
