openapi: 3.0.0

info:
  title: "dev navi API"
  version: "1.0.0"

paths:
  /login:
    get:
      summary: "Login"
      description: "Login to the dev navi with LINE account"
      operationId: "login"
      responses:
        "303":
          description: "Redirect to the app page"
  /logout:
    get:
      summary: "Logout"
      description: "Logout from the dev navi"
      operationId: "logout"
      responses:
        "303":
          description: "Redirect to the login page"
  /products:
    get:
      summary: "Get products"
      description: "Get users' products list"
      operationId: "getProducts"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/ProductResponse"
  /create-product:
    post:
      summary: "Create product"
      description: "Create a new product"
      operationId: "createProduct"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductRequest"
      responses:
        "201":
          description: "Created"
  /products/{product-id}:
    parameters:
      - $ref: "#/components/parameters/ProductId"
    get:
      summary: "Get product"
      description: "Get a product"
      operationId: "getProduct"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductDetailsResponse"
    post:
      summary: "Update product"
      description: "Update a product"
      operationId: "updateProduct"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductRequest"
      responses:
        "200":
          description: "OK"
    delete:
      summary: "Delete product"
      description: "Delete a product"
      operationId: "deleteProduct"
      responses:
        "200":
          description: "OK"

  /products/{product-id}/milestones/{milestone-id}:
    parameters:
      - $ref: "#/components/parameters/ProductId"
      - $ref: "#/components/parameters/MilestoneId"
    post:
      summary: "Create milestone"
      description: "Create a new milestone"
      operationId: "createMilestone"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MilestoneRequest"
      responses:
        "201":
          description: "Created"

components:
  schemas:
    ProductRequest:
      type: "object"
      properties:
        title:
          type: "string"
        deadline:
          type: "string"
        memo:
          type: "string"
      required:
        - title
        - deadline
        - memo

    MilestoneRequest:
      type: "object"
      properties:
        title:
          type: "string"
        deadline:
          type: "string"
      required:
        - title
        - deadline

    ProductResponse:
      type: "object"
      properties:
        id:
          type: "integer"
        title:
          type: "string"
        deadline:
          type: "string"
        memo:
          type: "string"
      required:
        - id
        - title
        - deadline
        - memo

    ProductDetailsResponse:
      type: "object"
      properties:
        id:
          type: "integer"
        title:
          type: "string"
        deadline:
          type: "string"
        memo:
          type: "string"
        milestones:
          type: "array"
          items:
            $ref: "#/components/schemas/MilestoneResponse"
      required:
        - id
        - title
        - deadline
        - memo
        - milestones

    MilestoneResponse:
      type: "object"
      properties:
        id:
          type: "integer"
        title:
          type: "string"
        deadline:
          type: "string"
      required:
        - id
        - title
        - deadline

  parameters:
    ProductId:
      name: "product-id"
      in: "path"
      required: true
      schema:
        type: "integer"
    MilestoneId:
      name: "milestone-id"
      in: "path"
      required: true
      schema:
        type: "integer"
