run:
  go: '1.22.2'
linters:
  enable-all: true
  disable:
    - deadcode
    - ifshort
    - structcheck
    - maligned
    - varcheck
    - exhaustivestruct
    - nosnakecase
    - golint
    - interfacer
    - scopelint